title: "Bayesian Preference Estimation"
description: "Paper presentation for Bayesian Preference Estimation with Inconsistent Feedback"
theme: jekyll-theme-cayman  # Or another theme of your choice

# Optional: Additional settings
show_excerpts: true
show_last_updated: true
