# Site settings
title: "Bayesian Preference Estimation With Inconsistent Feedback"
description: "Website for the paper 'Bayesian Preference Estimation with Inconsistent Feedback'"
url: "https://naghiaei.github.io/mixture-bayesian"
baseurl: "" # Leave empty unless you have a sub-path

# Build settings
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site author
author:
  name: "Mohammadmehdi Naghiaei"
  # avatar: "/assets/images/avatar.png" # Optional: Add your avatar
  bio: "PhD student in Industrial and System Engineering."

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
